---
# tasks file for tomcat
- name: Ensure Tomcat service package is present
  apt:
    name: {{ item }}
    state: present
  with_items:
    - default-jdk
    - tomcat9
    - git

- name: "Копирование файла war"
  synchronize:
    src: /mvn/target/hello-1.0.war
    dest: {{destination_folder}}
  delegate_to: "{{groups['build'][0]}}"
